server:
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 465
    protocol: smtps
